packages:
  - 'main' # 主应用 - WuJie 微前端
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'utils/*'
  - 'app/*' # 客户端应用
  - 'app-cli/*' # 脚手架工具
  - 'app-server/*' # 服务端应用
  - 'app-babel/*' # babel 插件
  - 'e2e'
  - 'e2e/demos/*'
