import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavLinks } from '@/app/ui/nav-links'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  auth,
  children
}: Readonly<{
  auth: React.ReactNode
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav>
          <NavLinks />
          <Link href='/login'>Open modal</Link>
        </nav>
        <div>{auth}</div>
        <main>{children}</main>
      </body>
    </html>
  )
}
